# Generated by Django 2.2.3 on 2020-07-10 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='其他', max_length=200, verbose_name='类名')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'db_table': 'PostCategory',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='其他', max_length=100, verbose_name='标签名')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogmes.Category', verbose_name='分类')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'db_table': 'Tag',
            },
        ),
        migrations.CreateModel(
            name='Specific_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('content', mdeditor.fields.MDTextField(verbose_name='内容')),
                ('read', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('like', models.IntegerField(default=0, verbose_name='点赞次数')),
                ('excerpt', models.CharField(blank=True, max_length=200, null=True, verbose_name='摘要')),
                ('pic', models.ImageField(db_column='post_pic', upload_to='blogmes', verbose_name='文章图片')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogmes.Category', verbose_name='类别')),
                ('tags', models.ManyToManyField(blank=True, to='blogmes.Tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'db_table': 'Specific_Post',
            },
        ),
        migrations.CreateModel(
            name='Banner_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('content', mdeditor.fields.MDTextField(verbose_name='内容')),
                ('pic', models.ImageField(db_column='bannner_pic', upload_to='bannner_mes', verbose_name='轮播图片')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '轮播图文章',
                'verbose_name_plural': '轮播图文章',
                'db_table': 'Banner_Post',
            },
        ),
    ]
