# Generated by Django 2.2.3 on 2020-07-08 08:24

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogmes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner_post',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='specific_post',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='内容'),
        ),
    ]
