# Generated by Django 2.2.3 on 2020-07-08 12:43

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blogmes', '0002_auto_20200708_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner_post',
            name='content',
            field=mdeditor.fields.MDTextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='specific_post',
            name='content',
            field=mdeditor.fields.MDTextField(verbose_name='内容'),
        ),
    ]
