# Generated by Django 2.2.3 on 2020-07-09 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blogmes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='文件名')),
                ('file', models.FileField(upload_to='File', verbose_name='文件')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogmes.Category', verbose_name='类别')),
            ],
            options={
                'verbose_name': '文件存储',
                'verbose_name_plural': '文件存储',
                'db_table': 'FileStore',
            },
        ),
    ]
