# Generated by Django 2.2.3 on 2020-07-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferfiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filestore',
            name='file',
            field=models.FileField(upload_to='File<django.db.models.fields.related.ForeignKey>/', verbose_name='文件'),
        ),
    ]
