# Generated by Django 2.2.3 on 2020-07-11 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transferfiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filestore',
            name='floader_cate',
            field=models.CharField(choices=[('T', 'tar'), ('PT', 'ppt'), ('PF', 'pdf'), ('W', 'word'), ('H', 'html'), ('O', 'other'), ('M', 'markdown')], default='O', max_length=2, verbose_name='文件类别'),
        ),
        migrations.AlterField(
            model_name='filestore',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transferfiles.Category', verbose_name='内容类别'),
        ),
    ]
